// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBENHg638Jw_QM0bFN6Daop3bgimWZ0Qi0',
    appId: '1:400517433579:web:accaa0b5eacd58094a96ae',
    messagingSenderId: '400517433579',
    projectId: 'cafe-review-73a3d',
    authDomain: 'cafe-review-73a3d.firebaseapp.com',
    storageBucket: 'cafe-review-73a3d.firebasestorage.app',
    measurementId: 'G-XEG7C2N46V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2P3MdRpLySEYl0YwCyBKErsDJllDjqI',
    appId: '1:400517433579:android:2521e354ffb8c4634a96ae',
    messagingSenderId: '400517433579',
    projectId: 'cafe-review-73a3d',
    storageBucket: 'cafe-review-73a3d.firebasestorage.app',
  );
}
